name: Build-Lint-Test
on:
  push:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - edited
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Get rep code
        uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - name: Test app
        run: npm run test
      - name: Lint code
        run: npm run lint
      - name: Build app
        run: npm run build
      - name: Deploy app
        run: echo Deploy
