name: Lint-Test-Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - edited
jobs:
  lint-test-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get rep code
        uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test app
        run: npm run test
      - name: Build app
        run: npm run build
      - name: Deploy app
        run: echo Deploy
